title: Edwin Tan - Portfolio
author: Edwin Tan
email: edwin_liberty84@hotmail.com
description: Edwin Tan - Artificial Intelligence, Machine Learning, Deep Learning, Computer Vision
url: "https://edwinliberty84.github.io"
github_username:  edwinliberty84
#google_analytics: UA-110543961-1

theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
